### ISSUE TITLE
靠近/离开 "大树干(watertree_pillar)" 会崩溃，应该是修改了玩家侦测组件的缘故，希望可以修复一下。

### ISSUE THREAD

**Issue by qians2** [donmor/libTimeStopper-mod-dst#1]
[00:05:21]: [string "scripts/prefabs/watertree_pillar.lua"]:82: attempt to index local 'player' (a nil value)
LUA ERROR stack traceback:
scripts/prefabs/watertree_pillar.lua:82 in (field) onfar (Lua) <81-87>
   inst = 109931 - watertree_pillar (valid:true)
   player = nil
scripts/components/playerprox.lua:57 in (upvalue) ptargetmode (Lua) <44-60>
   inst = 109931 - watertree_pillar (valid:true)
   self =
      onnear = function - scripts/prefabs/watertree_pillar.lua:89
      task = PERIODIC 109931: 0.333333
      onfar = function - scripts/prefabs/watertree_pillar.lua:81
      SetTargetMode = function - ../mods/workshop-2576514266/modmain.lua:215
      isclose = false
      near = 28
      period = 0.33333333333333
      inst = 109931 - watertree_pillar (valid:true)
      far = 29
      originaltargetmode = function - ../mods/workshop-2576514266/modmain.lua:216
      _ontargetleft = function - scripts/components/playerprox.lua:139
      targetmode = function - ../mods/workshop-2576514266/modmain.lua:216
      closeplayers = table: 00000000B9878070
   x = -192
   y = 0
   z = 195.75
../mods/workshop-2576514266/modmain.lua:218 in (field) fn (Lua) <216-220>
   inst = 109931 - watertree_pillar (valid:true)
   self =
      onnear = function - scripts/prefabs/watertree_pillar.lua:89
      task = PERIODIC 109931: 0.333333
      onfar = function - scripts/prefabs/watertree_pillar.lua:81
      SetTargetMode = function - ../mods/workshop-2576514266/modmain.lua:215
      isclose = false
      near = 28
      period = 0.33333333333333
      inst = 109931 - watertree_pillar (valid:true)
      far = 29
      originaltargetmode = function - ../mods/workshop-2576514266/modmain.lua:216
      _ontargetleft = function - scripts/components/playerprox.lua:139
      targetmode = function - ../mods/workshop-2576514266/modmain.lua:216
      closeplayers = table: 00000000B9878070
scripts/scheduler.lua:177 in (method) OnTick (Lua) <155-207>
   self =
      running = table: 000000000FAEFC90
      waitingfortick = table: 000000000FAF0870
      tasks = table: 000000000FAEFA60
      waking = table: 00000000C1B23370
      attime = table: 000000000FAF08C0
      hibernating = table: 000000000FAEFB50
   tick = 5438
   k = PERIODIC 109931: 0.333333
   v = true
   already_dead = nil
scripts/scheduler.lua:371 in (global) RunScheduler (Lua) <369-377>
   tick = 5438
scripts/update.lua:191 in () ? (Lua) <170-249>
   dt = 0.033333335071802
   tick = 5438
   i = 5438

[00:05:21]: [string "scripts/prefabs/watertree_pillar.lua"]:82: attempt to index local 'player' (a nil value)
LUA ERROR stack traceback:
    scripts/prefabs/watertree_pillar.lua:82 in (field) onfar (Lua) <81-87>
    scripts/components/playerprox.lua:57 in (upvalue) ptargetmode (Lua) <44-60>
    ../mods/workshop-2576514266/modmain.lua:218 in (field) fn (Lua) <216-220>
    scripts/scheduler.lua:177 in (method) OnTick (Lua) <155-207>
    scripts/scheduler.lua:371 in (global) RunScheduler (Lua) <369-377>
    scripts/update.lua:191 in () ? (Lua) <170-249>
	
[00:05:21]: Force aborting...

**Comment by donmor** [comment]
已定位并修复，将在下一版本应用

**Comment by donmor** [comment]
最新commit已推送，有空的话clone一个master的版本试试修复了没 :)

**Comment by qians2** [comment]
试了一下这个问题已经解决了

**Comment by donmor** [comment]
行 回头出release

**Comment by donmor** [comment]
已上传
